### PR TITLE
feat: add "DELETE ../access_method/{access_id}"

### LINKED ISSUE #27: Implement "DELETE /objects/{object_id}/access/{access_id}"
### Description

As in issue #10 and PR #9, but for deleting an access method rather than an object. Note that at least one access method always has to be available for a given object.

### Proposed solution

- Add an endpoint `DELETE /objects/{object_id}/access/{access_id}` to the custom [DRS-Filer specification](https://github.com/elixir-cloud-aai/drs-filer/blob/8cc77d360a0d25e164a63feabf7b5bbdc90a6236/drs_filer/api/additional.data_repository_service.swagger.yaml#L76).
- Implement the controller for the new endpoint
- Ensure that the last available access method cannot be deleted (issue a `400/BadRequest` response if attempted to)
- Add/update unit tests

Compare the [`DELETE /tools/{id}/versions/{version_id}` controller](https://github.com/elixir-cloud-aai/trs-filer/blob/2158df4f2a8bd6850d0a9fc20a13dd6ad205e276/trs_filer/ga4gh/trs/server.py#L610) for an example on how to make sure that the last list item (here: a tool version) cannot be deleted.

### PR DESCRIPTION
**Pull request by chinvib66**
## Description

- add specs for `DELETE /objects/{object_id}/access/{access_id}` endpoint
- implement endpoint logic and tests

Resolves #27

### CODE REVIEW

**Comment by chinvib66** [comment]
@uniqueg PR ready for review

**Comment by uniqueg** [comment]
This looks really nice @chinvib66! Will have a detailed look and a manual integration test later on tonight or latest tomorrow and add the test for the missing line (unless you wanna do it yourself). But thanks a lot already 🙏🏻

**Comment by chinvib66** [comment]
@uniqueg I couldn't figure out how to cover that line. 

It's for internal server error if db update_one fails for some reason. [Line 147](https://github.com/elixir-cloud-aai/drs-filer/pull/30/files#diff-80f31230b9e487db2036dece253d7093R144)

**Comment by uniqueg** [comment]
Ah, thanks, @chinvib66, saves me some time checking this. Guess the way is to mock up the response of `update_one()`. I'll figure it out!
If you are interested in these kind of things (healthcare-related interoperable API microservices), let me know - I think we got a pretty interesting project going on. If you like, you can check those slides for details: https://docs.google.com/presentation/d/1y-dYxz0aZ1TnASQzT2wZ99agTY2z6jaixZG4ZNQ-zFg/

**Review by uniqueg — APPROVED** [review]
Thanks a lot @chinvib66. Refactored a bit and added the test for the missing statement.

**Pull request merged**
