### PR TITLE
docs: add additional sections

### LINKED ISSUE #33: Extend documentation
Hello! The lack of `Usage` and `Description` syntax on the README.md are a hint that this project is not yet finished/operational? :)

```
% docker compose up
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
[+] Building 0.0s (0/0)
WARN[0001] invalid non-bool value for BUILDX_NO_DEFAULT_LOAD:
[+] Building 124.6s (12/12) FINISHED
 => [mongodb internal] load build definition from Dockerfile                                                                                               0.2s
 => => transferring dockerfile: 51B                                                                                                                        0.0s
 => [drs-filer_drs internal] load build definition from Dockerfile                                                                                         0.1s
 => => transferring dockerfile: 687B                                                                                                                       0.0s
 => [mongodb internal] load .dockerignore                                                                                                                  0.2s
 => => transferring context: 291B                                                                                                                          0.0s
 => [drs-filer_drs internal] load .dockerignore                                                                                                            0.1s
 => => transferring context: 291B                                                                                                                          0.0s
 => [mongodb internal] load metadata for docker.io/library/mongo:3.6                                                                                       4.1s
 => [drs-filer_drs internal] load metadata for docker.io/elixircloud/foca:latest                                                                           0.0s
 => [drs-filer_drs internal] load build context                                                                                                            0.1s
 => => transferring context: 95.48kB                                                                                                                       0.1s
 => [drs-filer_drs 1/3] FROM docker.io/elixircloud/foca:latest                                                                                             0.3s
 => => resolve docker.io/elixircloud/foca:latest                                                                                                           0.0s
 => [drs-filer_drs 2/3] COPY ./ /app                                                                                                                       0.1s
 => [drs-filer_drs 3/3] RUN cd /app   && python setup.py develop   && cd /   && chmod g+w /app/drs_filer/api/   && pip install yq                         16.7s
 => [mongodb 1/1] FROM docker.io/library/mongo:3.6@sha256:563ee704d05010d88fc97d66cf925271f0fcb0facc42f15f26ff95e08b353359                               119.8s
 => => resolve docker.io/library/mongo:3.6@sha256:563ee704d05010d88fc97d66cf925271f0fcb0facc42f15f26ff95e08b353359                                         0.0s
 => => sha256:be8ec4e48d7f24a9a1c01063e5dfabb092c2c1ec73e125113848553c9b07eb8c 45.84MB / 45.84MB                                                          49.0s
 => => sha256:33b8b485aff0509bb0fa67dff6a2aa82e9b7b17e5ef28c1673467ec83edb945d 849B / 849B                                                                 2.5s
 => => sha256:430ca129e871928612d68421cde25519d8b71e2937c9ad28eae34dc0571145e1 9.68kB / 9.68kB                                                             0.0s
 => => sha256:563ee704d05010d88fc97d66cf925271f0fcb0facc42f15f26ff95e08b353359 1.04kB / 1.04kB                                                             0.0s
 => => sha256:d887158cc58cbfc3d03cefd5c0b15175fae66ffbf6f28a56180c51cbb5062b8a 533B / 533B                                                                 2.8s
 => => sha256:e6ded0eb101c09489714ace170f7fbb2c42a78c9bf04cfeab5d00bd9a9b2fa0f 3.03kB / 3.03kB                                                             0.0s
 => => sha256:05895bb28c18264f614acd13e401b3c5594e12d9fe90d7e52929d3e810e11e97 167B / 167B                                                                 3.2s
 => => sha256:554956c5520b91826f67a69c857085abe6308b305bf724001852f30444d1d240 1.99kB / 1.99kB                                                             4.6s
 => => sha256:1129bf37b6f0e8c688cffb0577d721030022a07ff49f5ecf1b80879039bca187 2.92MB / 2.92MB                                                             8.7s
 => => sha256:0a961c831444b5f831645776d13caf4e607cc03e471e87ab6a68bd98dd55d3f4 1.31MB / 1.31MB                                                             7.6s
 => => sha256:002e342bfc39f4560472f645a1173cd67daa71236e97f479ab407ffa5b8e489d 115B / 115B                                                                 8.2s
 => => sha256:67b67cb953c65f1761bc5fa7c37f51b8f9ae4d0028d3735814c28c1ed91e0a2a 1.99kB / 1.99kB                                                             8.6s
 => => sha256:35ef1c541d5d070f57546e35a709bbf08f369d0ebe0ef5a7b45f8545001b5e58 237B / 237B                                                                 9.0s
 => => sha256:34397889ad3a6209e4a57d2f618f57ffea691fbf53b55ac03d901baf32021a1f 117.88MB / 117.88MB                                                       100.0s
 => => sha256:8d302d4d0319793b0358b6b1de9f6a8b2c0a795b04fdcdca13bdce2ccc8d9c61 139B / 139B                                                                 9.7s
 => => sha256:04763b39e569666bc94a5479cc9ce003377b2762c0f476e8cbd863fbcabaa6b4 4.42kB / 4.42kB                                                            10.3s
 => => extracting sha256:be8ec4e48d7f24a9a1c01063e5dfabb092c2c1ec73e125113848553c9b07eb8c                                                                 12.4s
 => => extracting sha256:33b8b485aff0509bb0fa67dff6a2aa82e9b7b17e5ef28c1673467ec83edb945d                                                                  0.0s
 => => extracting sha256:d887158cc58cbfc3d03cefd5c0b15175fae66ffbf6f28a56180c51cbb5062b8a                                                                  0.0s
 => => extracting sha256:05895bb28c18264f614acd13e401b3c5594e12d9fe90d7e52929d3e810e11e97                                                                  0.0s
 => => extracting sha256:554956c5520b91826f67a69c857085abe6308b305bf724001852f30444d1d240                                                                  0.0s
 => => extracting sha256:1129bf37b6f0e8c688cffb0577d721030022a07ff49f5ecf1b80879039bca187                                                                  1.0s
 => => extracting sha256:0a961c831444b5f831645776d13caf4e607cc03e471e87ab6a68bd98dd55d3f4                                                                  0.7s
 => => extracting sha256:002e342bfc39f4560472f645a1173cd67daa71236e97f479ab407ffa5b8e489d                                                                  0.0s
 => => extracting sha256:67b67cb953c65f1761bc5fa7c37f51b8f9ae4d0028d3735814c28c1ed91e0a2a                                                                  0.0s
 => => extracting sha256:35ef1c541d5d070f57546e35a709bbf08f369d0ebe0ef5a7b45f8545001b5e58                                                                  0.0s
 => => extracting sha256:34397889ad3a6209e4a57d2f618f57ffea691fbf53b55ac03d901baf32021a1f                                                                 18.4s
 => => extracting sha256:8d302d4d0319793b0358b6b1de9f6a8b2c0a795b04fdcdca13bdce2ccc8d9c61                                                                  0.0s
 => => extracting sha256:04763b39e569666bc94a5479cc9ce003377b2762c0f476e8cbd863fbcabaa6b4                                                                  0.0s
 => [mongodb] exporting to image                                                                                                                           0.1s
 => => exporting layers                                                                                                                                    0.0s
 => => writing image sha256:8bfa03a4149d3e6793c694fa77d80a81bc2b69bbe0560891ef2e6344f8ce7423                                                               0.0s
 => => naming to docker.io/library/drs-filer_drs                                                                                                           0.0s
 => => writing image sha256:084967e34476679085885890c3cd69a8675d17f66e8993b2587fed5c73fdf75c                                                               0.0s
 => => naming to docker.io/library/mongo:3.6                                                                                                               0.0s
[+] Running 1/2
 ⠿ Network "drs-filer_default"  Created                                                                                                                    0.4s
 ⠹ drs-filer_mongodb_1          Creating                                                                                                                   0.2s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/rvalls/dev/umccr/data/drs/db
```

### PR DESCRIPTION
**Pull request by psankhe28**
## Description

Add missing sections to `README.md`, namely: "Usage", "Installation" and "Deployment"

Fixes #33 

## Type of change

- [x] Documentation update

## Checklist:

- [ ] My code follows the [style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md#language-specific-guidelines) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not reduced the existing code coverage
- [x] I have added docstrings following the [Python style guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/python.md) of this project to all new modules, classes, methods and functions are documented with docstrings following; I have updated any previously existing docstrings, if applicable
- [x] I have updated any sections of the app's documentation that are affected by the proposed changes, if applicable

### CODE REVIEW

**Review by uniqueg — APPROVED** [review]
LGTM, thanks a lot :)

**Comment by uniqueg** [comment]
@psankhe28: Please follow the (updated) [commit message guidelines](https://elixir-cloud-aai.github.io/guides/guide-contributor/workflow/#commit-messages) for your PR titles in the future.

FYI, your PR title did not follow the following rules:

- Keep your entire header/title line (including type and, if available, scope) at **50 characters or less**
- Only use types `feat`, `fix`, `perf`, `refactor` and `style` for changes in package/production code; use the dedicated types for all build-, CI-, documentation- or test-related changes
- Start the `<description>` with a verb in imperative form (e.g., `add`, `fix`)

**Comment by uniqueg** [comment]
Also, if you think that your PR fixes #33, please indicate so in your PR description, e.g., `Fixes #33`. If it does not address any issue, please remove the `Fixes # (issue)` placeholder from your PR description, but not that usually, every PR should have one or more issues it addresses/fixes (so write one before raising a pull request). In this case, it's fine though.

You could also say that this PR `Partly addresses #33`.

**Comment by psankhe28** [comment]
I have made the changes, please have a look and let me know. Thanks!

**Pull request merged**
